apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 444
    targetPort: 444