apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 10
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontendapp
        image: hasankarademir/frontend-app:latest
        ports:
        - containerPort:  80
          name: frontend
